- name: Preparing the VM to be migrated to Azure
  become: true
  become_method: sudo
  hosts: nodes
  force_handlers: True
  tasks:
    - name: uninstall-NetworkManager
      yum:
        name: NetworkManager
        state: removed
    - name: create-sysconfig-network-file
      file:
        path: /etc/sysconfig/network
        state: touch
    - name: add-sysconfig-network
      copy:
        content: |
          NETWORKING=yes
          HOSTNAME=localhost.localdomain
        dest: /etc/sysconfig/network
​
    - name: network-script-ifcfg-eth0 ispresent
      command: grep -Fxq "DEVICE=eth0
          ONBOOT=yes
          BOOTPROTO=dhcp
          TYPE=Ethernet
          USERCTL=no
          PEERDNS=yes
          IPV6INIT=no" /etc/sysconfig/network-scripts/ifcfg-eth0
      register: checkmyconf
      check_mode: no
      ignore_errors: yes
      changed_when: no
​
    - name: network-script-ifcfg-eth0
      register: checkmyconf
      lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-eth0
        line: |
          DEVICE=eth0
          ONBOOT=yes
          BOOTPROTO=dhcp
          TYPE=Ethernet
          USERCTL=no
          PEERDNS=yes
          IPV6INIT=no
      when: checkmyconf.rc == 0 ## do not run this tasks
    
    - name: remove-udev-rules
      command:
        argv:
          - ln
          - -s
          - /dev/null
          - /etc/udev/rules.d/75-persistent-net-generator.rules
      when: false ## do not run this tasks
​
    - name: delete-70-persistent-net.rules
      file:
        path: /etc/udev/rules.d/70-persistent-net.rules
        state: absent
​
    - name: network-service-start-boot
      command:
        argv:
          - subscription-manager 
          - register 
          - --auto-attach 
          - --username=XXX 
          - --password=XXX
      when: false
    - name: Register-subscription
      command:
        argv:
          - echo
          - hi
      when: false
    
    - name: add-WALinuxAgent-repo
      command:
        argv:
          - subscription-manager
          - repos
          - --enable=rhel-6-server-extras-rpms 
      when: false
    
    - name: install-WALinuxAgent
      command:
        argv:
          - yum 
          - install 
          - -y
          - WALinuxAgent
​
    - name: Create-kernel-boot 
      file:
        path: /boot/grub/menu.lst
        state: touch
      when: false
    - name: Modify-kernel-boot 
      lineinfile:
        path: /boot/grub/menu.lst
        line: |
          console=ttyS0 earlyprintk=ttyS0 rootdelay=300
      when: false
    - name: remove-kernel param
      replace:
        path: /boot/grub/menu.lst
        regexp: 'rhgb quiet crashkernel=auto'
        replace: ''
      when: false
    - name: configure-secure-shell
      lineinfile:
        path: /etc/ssh/sshd_config
        line: |
          ClientAliveInterval 180
      when: false
​
    - name: update-vm
      command:
        argv: 
          - yum
          - update
          - -y
    - name: install-azure-agent
      command:
        argv: 
          - yum
          - install
          - -y
          - WALinuxAgent
    - name: start-waagent
      command:
        argv:
          - chkconfig
          - waagent
          - "on"
​
    - name: config-swap
      lineinfile: 
        path: /etc/waagent.conf 
        line: |
                ResourceDisk.Format=y
                ResourceDisk.Filesystem=ext4
                ResourceDisk.MountPoint=/mnt/resource
                ResourceDisk.EnableSwap=y
                ResourceDisk.SwapSizeMB=2048    ## NOTE: set this to whatever you need it to be.
​
    - name: Unregister the subscription 
      command:
        argv:
          = subscription-manager
          - unregister
    - name: deprovision-for-creating-general-image
      command:
        argv:
          - waagent 
          - -force 
          - -deprovision
      when: false
    - name: deprovision-export
      command:
        argv:
          - export
          - HISTSIZE=0
